# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vsearch/protos/shard.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'vsearch/protos/shard.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1avsearch/protos/shard.proto\x12\x07vsearch\"=\n\nAddRequest\x12\x12\n\nglobal_ids\x18\x01 \x03(\x03\x12\x0b\n\x03\x64im\x18\x02 \x01(\x05\x12\x0e\n\x06values\x18\x03 \x03(\x02\"\x1b\n\x0b\x41\x64\x64Response\x12\x0c\n\x04size\x18\x01 \x01(\x03\")\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x03(\x02\x12\t\n\x01k\x18\x02 \x01(\x05\"*\n\x03Hit\x12\x11\n\tglobal_id\x18\x01 \x01(\x03\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\",\n\x0eSearchResponse\x12\x1a\n\x04hits\x18\x01 \x03(\x0b\x32\x0c.vsearch.Hit2{\n\x0cShardService\x12\x30\n\x03\x41\x64\x64\x12\x13.vsearch.AddRequest\x1a\x14.vsearch.AddResponse\x12\x39\n\x06Search\x12\x16.vsearch.SearchRequest\x1a\x17.vsearch.SearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vsearch.protos.shard_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=39
  _globals['_ADDREQUEST']._serialized_end=100
  _globals['_ADDRESPONSE']._serialized_start=102
  _globals['_ADDRESPONSE']._serialized_end=129
  _globals['_SEARCHREQUEST']._serialized_start=131
  _globals['_SEARCHREQUEST']._serialized_end=172
  _globals['_HIT']._serialized_start=174
  _globals['_HIT']._serialized_end=216
  _globals['_SEARCHRESPONSE']._serialized_start=218
  _globals['_SEARCHRESPONSE']._serialized_end=262
  _globals['_SHARDSERVICE']._serialized_start=264
  _globals['_SHARDSERVICE']._serialized_end=387
# @@protoc_insertion_point(module_scope)
