# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from vsearch.protos import shard_pb2 as vsearch_dot_protos_dot_shard__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vsearch/protos/shard_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShardServiceStub:
    """One shard of the index, served by its own process.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/vsearch.ShardService/Add',
                request_serializer=vsearch_dot_protos_dot_shard__pb2.AddRequest.SerializeToString,
                response_deserializer=vsearch_dot_protos_dot_shard__pb2.AddResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/vsearch.ShardService/Search',
                request_serializer=vsearch_dot_protos_dot_shard__pb2.SearchRequest.SerializeToString,
                response_deserializer=vsearch_dot_protos_dot_shard__pb2.SearchResponse.FromString,
                _registered_method=True)


class ShardServiceServicer:
    """One shard of the index, served by its own process.
    """

    def Add(self, request, context):
        """Store a batch of vectors in this shard.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Return this shard's k nearest neighbors of the query.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=vsearch_dot_protos_dot_shard__pb2.AddRequest.FromString,
                    response_serializer=vsearch_dot_protos_dot_shard__pb2.AddResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=vsearch_dot_protos_dot_shard__pb2.SearchRequest.FromString,
                    response_serializer=vsearch_dot_protos_dot_shard__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vsearch.ShardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vsearch.ShardService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShardService:
    """One shard of the index, served by its own process.
    """

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vsearch.ShardService/Add',
            vsearch_dot_protos_dot_shard__pb2.AddRequest.SerializeToString,
            vsearch_dot_protos_dot_shard__pb2.AddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vsearch.ShardService/Search',
            vsearch_dot_protos_dot_shard__pb2.SearchRequest.SerializeToString,
            vsearch_dot_protos_dot_shard__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
